### ISSUE TITLE
Rows is not showed on the first load

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#30]
On the first loading, rows are not showed.

![image](https://user-images.githubusercontent.com/11459051/27509139-e5fce2a4-58fe-11e7-9840-fafb69c79143.png)

It should show 5 rows as selected by default.

**Comment by RSmetanyuk** [comment]
You need to push "Start". It is the bug, that other cases are showing without pushing the start button (because in the form used "onchange" function, when clicked "5" there is no changes and function is not started).

**Comment by i10111pn** [comment]
"(because in the form used "onchange" function, when clicked "5" there is no changes and **function** is not started)."

call this **function** on application start.

**Comment by RSmetanyuk** [comment]
I think that commit #31 resolved the problem

**Comment by i10111pn** [comment]
No, it did not.

**Comment by RSmetanyuk** [comment]
done. commit #25

**Comment by i10111pn** [comment]
It still not showing rows on the first load.

![image](https://user-images.githubusercontent.com/11459051/27905493-c6fa28f0-6248-11e7-9b30-3ea5e5aa4d58.png)

**Comment by RSmetanyuk** [comment]
Do you want to see 5 empty rows?

**Comment by i10111pn** [comment]
No, it should show first 5 rows.

**Comment by RSmetanyuk** [comment]
![image](https://user-images.githubusercontent.com/29253760/27917560-ff2194c6-6274-11e7-861c-d79d5d808029.png)

**Comment by RSmetanyuk** [comment]
I was added

window.onload = function() {
  main();
};

**Comment by i10111pn** [comment]
Let me check.
