### ISSUE TITLE
'Go to the bottom' button is not showed

### ISSUE THREAD

**Issue by i10111pn** [RSmetanyuk/myapp#48]
**Steps to reproduce:**
1. Select to show all rows in 'Rows per page'

**Expected behavior:**
'Go to the bottom' button is showed.

**Current behavior:**
'Go to the bottom' button is not showed.

![image](https://user-images.githubusercontent.com/11459051/27975202-f10d2846-6369-11e7-91e4-6d62e0f1e987.png)

**Comment by RSmetanyuk** [comment]
Can change the size of the window or content. In both cases, it appears scrolled. How to describe the event occurrence scrolls?

**Comment by i10111pn** [comment]
No, try to avoid window/content size changing.

**Comment by RSmetanyuk** [comment]
Done

**Comment by i10111pn** [comment]
The bug is still present.

![image](https://user-images.githubusercontent.com/11459051/28191492-46ab2a90-6839-11e7-9239-35dae2a8b3f4.png)

**Comment by RSmetanyuk** [comment]
In task was:
Steps to reproduce:
Select to show **all rows** in 'Rows per page'

**Comment by RSmetanyuk** [comment]
I am difficult to describe the trigger of appearance the scroll

**Comment by i10111pn** [comment]
It doesn't matter, select [any number] to make scroll appears. 
If you have others tasks to do then skip this one for a while.

**Comment by RSmetanyuk** [comment]
Done.
